/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditorMainMenuPanel.java
 *
 * Created on 13.jul.2012, 21:23:43
 */
package editor.gui;

import java.awt.Font;

/**
 *
 * @author Bart
 */
public class MainMenuView extends javax.swing.JPanel {

	/** Creates new form EditorMainMenuPanel */
	public MainMenuView() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		createNewButton = new javax.swing.JButton();
		titleLabel = new javax.swing.JLabel();
		editorTextLabel = new javax.swing.JLabel();
		rowsLabel = new javax.swing.JLabel();
		rowsScrollPane = new javax.swing.JScrollPane();
		rowsTextPane = new javax.swing.JTextPane();
		columnsLabel = new javax.swing.JLabel();
		columnsScrollPane = new javax.swing.JScrollPane();
		columnsTextPane = new javax.swing.JTextPane();
		editCurrentButton = new javax.swing.JButton();

		setName("Form"); // NOI18N

		createNewButton.setText("Create new"); // NOI18N
		titleLabel.setFont(new Font("Tahoma", Font.BOLD, 13)); // NOI18N
		titleLabel.setText("CoopPuzzler puzzle editor"); // NOI18N
		editorTextLabel.setText("<html>For creating a new puzzle, write down its size, and click on 'Create new'.<br>" +
								"For editing the current puzzle, click on 'Edit Current'.</html>"); // NOI18N
		rowsLabel.setText("Rows:    "); // NOI18N
		rowsScrollPane.setViewportView(rowsTextPane);
		columnsLabel.setText("Columns:"); // NOI18N
		columnsScrollPane.setViewportView(columnsTextPane);
		editCurrentButton.setText("Edit current"); // NOI18N

		 javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	        this.setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(titleLabel)
	                .addContainerGap(58, Short.MAX_VALUE))
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
	                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
	                        .addComponent(columnsLabel)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addComponent(columnsScrollPane))
	                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
	                        .addComponent(rowsLabel)
	                        .addGap(18, 18, 18)
	                        .addComponent(rowsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                .addContainerGap(112, Short.MAX_VALUE))
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(editCurrentButton)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addComponent(createNewButton))
	                    .addComponent(editorTextLabel))
	                .addContainerGap())
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(titleLabel)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(editorTextLabel)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(rowsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addComponent(columnsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(rowsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addComponent(columnsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                .addGap(12, 12, 12)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(createNewButton)
	                    .addComponent(editCurrentButton))
	                .addContainerGap())
	        );
	    }// </editor-fold>
	// Variables declaration - do not modify
	public static javax.swing.JLabel columnsLabel;
    public static javax.swing.JScrollPane columnsScrollPane;
    public static javax.swing.JTextPane columnsTextPane;
    public static javax.swing.JButton createNewButton;
    public static javax.swing.JButton editCurrentButton;
    public static javax.swing.JLabel editorTextLabel;
    public static javax.swing.JLabel rowsLabel;
    public static javax.swing.JScrollPane rowsScrollPane;
    public static javax.swing.JTextPane rowsTextPane;
    public static javax.swing.JLabel titleLabel;
	// End of variables declaration
}
