package client.gui;

import java.awt.Font;

/**
 *
 * @author Bart
 */
public class EditorMainMenuView extends javax.swing.JPanel {

	private static EditorMainMenuView instance;
	/** Creates new form EditorMainMenuPanel */
	public EditorMainMenuView() {
		initComponents();
		this.instance = this;
	}
	
	public static EditorMainMenuView getInstance() {
		return instance;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		titleLabel = new javax.swing.JLabel();
		separator = new javax.swing.JSeparator();
		editorDescriptionText = new javax.swing.JLabel();
		newPuzzlePanel = new javax.swing.JPanel();
		nameLabel = new javax.swing.JLabel();
		nameScollPane = new javax.swing.JScrollPane();
		nameTextPane = new javax.swing.JTextPane();
		rowsScrollPane = new javax.swing.JScrollPane();
		rowsTextPane = new javax.swing.JTextPane();
		rowsLabel = new javax.swing.JLabel();
		columnsScrollPane = new javax.swing.JScrollPane();
		columnsTextPane = new javax.swing.JTextPane();
		columnsLabel = new javax.swing.JLabel();
		createNewButton = new javax.swing.JButton();
		existingPuzzlePanel = new javax.swing.JPanel();
		existingScrollPane = new javax.swing.JScrollPane();
		existingPuzzleList = new javax.swing.JList();
		editCurrentButton = new javax.swing.JButton();
		newPuzzleHeader = new javax.swing.JLabel();
		existingPuzzleHeader = new javax.swing.JLabel();
		mainMenuButton = new javax.swing.JButton();

		setName("Form"); // NOI18N
		setPreferredSize(new java.awt.Dimension(520, 255));
		
		Font titleFont = new Font("Tahoma", Font.BOLD, 14);
		Font headerFont = new Font("Tahoma", Font.BOLD, 11);

		titleLabel.setFont(titleFont); // NOI18N
		titleLabel.setText("Puzzle Editor"); // NOI18N
		titleLabel.setName("titleLabel"); // NOI18N

		separator.setOrientation(javax.swing.SwingConstants.VERTICAL);
		separator.setName("separator"); // NOI18N

		editorDescriptionText.setText("To edit a puzzle, create a new one, or modify one you created before."); // NOI18N
		editorDescriptionText.setName("editorDescriptionText"); // NOI18N

		newPuzzlePanel.setName("newPuzzlePanel"); // NOI18N

		nameLabel.setText("Name:"); // NOI18N
		nameLabel.setName("nameLabel"); // NOI18N

		nameScollPane.setName("nameScollPane"); // NOI18N

		nameTextPane.setName("nameTextPane"); // NOI18N
		nameScollPane.setViewportView(nameTextPane);

		rowsScrollPane.setName("rowsScrollPane"); // NOI18N

		rowsTextPane.setName("rowsTextPane"); // NOI18N
		rowsScrollPane.setViewportView(rowsTextPane);

		rowsLabel.setText("Rows"); // NOI18N
		rowsLabel.setName("rowsLabel"); // NOI18N

		columnsScrollPane.setName("columnsScrollPane"); // NOI18N

		columnsTextPane.setName("columnsTextPane"); // NOI18N
		columnsScrollPane.setViewportView(columnsTextPane);

		columnsLabel.setText("Columns"); // NOI18N
		columnsLabel.setName("columnsLabel"); // NOI18N

		createNewButton.setText("Create New"); // NOI18N
		createNewButton.setName("createNewButton"); // NOI18N

		javax.swing.GroupLayout newPuzzlePanelLayout = new javax.swing.GroupLayout(newPuzzlePanel);
		newPuzzlePanel.setLayout(newPuzzlePanelLayout);
		newPuzzlePanelLayout.setHorizontalGroup(
				newPuzzlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(newPuzzlePanelLayout.createSequentialGroup()
						.addGroup(newPuzzlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(newPuzzlePanelLayout.createSequentialGroup()
										.addGroup(newPuzzlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(nameLabel)
												.addComponent(columnsLabel)
												.addComponent(rowsLabel))
												.addGap(15, 15, 15)
												.addGroup(newPuzzlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(nameScollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(newPuzzlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
																.addComponent(columnsScrollPane)
																.addComponent(rowsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))))
																.addComponent(createNewButton))
																.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);
		newPuzzlePanelLayout.setVerticalGroup(
				newPuzzlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(newPuzzlePanelLayout.createSequentialGroup()
						.addGroup(newPuzzlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(nameScollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
								.addComponent(nameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(newPuzzlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(rowsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
										.addComponent(rowsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(newPuzzlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(columnsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
												.addComponent(columnsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(createNewButton)
												.addContainerGap())
				);

		existingPuzzlePanel.setName("existingPuzzlePanel"); // NOI18N

		existingScrollPane.setName("existingScrollPane"); // NOI18N

		existingPuzzleList.setName("existingPuzzleList"); // NOI18N
		existingScrollPane.setViewportView(existingPuzzleList);

		editCurrentButton.setText("Edit selected"); // NOI18N
		editCurrentButton.setName("editCurrentButton"); // NOI18N

		javax.swing.GroupLayout existingPuzzlePanelLayout = new javax.swing.GroupLayout(existingPuzzlePanel);
		existingPuzzlePanel.setLayout(existingPuzzlePanelLayout);
		existingPuzzlePanelLayout.setHorizontalGroup(
				existingPuzzlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(existingPuzzlePanelLayout.createSequentialGroup()
						.addGroup(existingPuzzlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(existingScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(editCurrentButton))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);
		existingPuzzlePanelLayout.setVerticalGroup(
				existingPuzzlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(existingPuzzlePanelLayout.createSequentialGroup()
						.addComponent(existingScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(editCurrentButton)
						.addContainerGap())
				);

		newPuzzleHeader.setFont(headerFont); // NOI18N
		newPuzzleHeader.setText("Create a new puzzle:"); // NOI18N
		newPuzzleHeader.setName("newPuzzleHeader"); // NOI18N

		existingPuzzleHeader.setFont(headerFont); // NOI18N
		existingPuzzleHeader.setText("Edit an existing one"); // NOI18N
		existingPuzzleHeader.setName("existingPuzzleHeader"); // NOI18N

		mainMenuButton.setText("< Main Menu"); // NOI18N
		mainMenuButton.setName("jButton1"); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(newPuzzlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(6, 6, 6)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(existingPuzzleHeader)
												.addComponent(existingPuzzlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addComponent(editorDescriptionText)
												.addComponent(newPuzzleHeader)
												.addGroup(layout.createSequentialGroup()
														.addComponent(mainMenuButton)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(titleLabel)))
														.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(mainMenuButton)
								.addComponent(titleLabel))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(editorDescriptionText)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(newPuzzleHeader)
										.addComponent(existingPuzzleHeader))
										.addGap(12, 12, 12)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(newPuzzlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(existingPuzzlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addContainerGap())
				);
	}// </editor-fold>
	// Variables declaration - do not modify
	public static javax.swing.JLabel columnsLabel;
	public static javax.swing.JScrollPane columnsScrollPane;
	public static javax.swing.JTextPane columnsTextPane;
	public static javax.swing.JButton createNewButton;
	public static javax.swing.JButton editCurrentButton;
	public static javax.swing.JLabel editorDescriptionText;
	public static javax.swing.JLabel existingPuzzleHeader;
	public static javax.swing.JList existingPuzzleList;
	public static javax.swing.JPanel existingPuzzlePanel;
	public static javax.swing.JScrollPane existingScrollPane;
	public static javax.swing.JButton mainMenuButton;
	public static javax.swing.JLabel nameLabel;
	public static javax.swing.JScrollPane nameScollPane;
	public static javax.swing.JTextPane nameTextPane;
	public static javax.swing.JLabel newPuzzleHeader;
	public static javax.swing.JPanel newPuzzlePanel;
	public static javax.swing.JLabel rowsLabel;
	public static javax.swing.JScrollPane rowsScrollPane;
	public static javax.swing.JTextPane rowsTextPane;
	public static javax.swing.JSeparator separator;
	public static javax.swing.JLabel titleLabel;
	// End of variables declaration


}
