/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainMenuPanel.java
 *
 * Created on 23.des.2012, 14:59:46
 */
package client.gui;

import java.awt.Font;

/**
 *
 * @author Bart
 */
public class MainMenuView extends javax.swing.JPanel {

    /** Creates new form MainMenuPanel */
    public MainMenuView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        Font boldFont = new Font("Tahoma", Font.BOLD, 11);
        Font mainMenuFont = new Font("Tahoma", Font.BOLD, 18);
    	
    	
        mainMenuLabel = new javax.swing.JLabel();
        playLocalGameLabel = new javax.swing.JLabel();
        puzzleListScrollPane = new javax.swing.JScrollPane();
        puzzleList = new javax.swing.JList();
        playButton = new javax.swing.JButton();
        puzzleListDescriptionLabel = new javax.swing.JLabel();
        mainSeparator = new javax.swing.JSeparator();
        playGameOnServer = new javax.swing.JLabel();
        serverAddressLabel = new javax.swing.JLabel();
        serverAddressScrollPane = new javax.swing.JScrollPane();
        serverAddressTextBox = new javax.swing.JTextPane();
        connectToServerButton = new javax.swing.JButton();
        editPuzzleButton = new javax.swing.JButton();
        postPaneScrollPane = new javax.swing.JScrollPane();
        portTextField = new javax.swing.JTextPane();
        portLabel = new javax.swing.JLabel();
        createServerButton = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 241));

        mainMenuLabel.setFont(mainMenuFont); // NOI18N
        mainMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainMenuLabel.setText("Main Menu"); // NOI18N
        mainMenuLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mainMenuLabel.setName("mainMenuLabel"); // NOI18N

        playLocalGameLabel.setFont(boldFont); // NOI18N
        playLocalGameLabel.setText("Play local game"); // NOI18N
        playLocalGameLabel.setName("playLocalGameLabel"); // NOI18N

        puzzleListScrollPane.setName("puzzleListScrollPane"); // NOI18N

        puzzleList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Failed to list puzzles" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        puzzleList.setName("puzzleList"); // NOI18N
        puzzleListScrollPane.setViewportView(puzzleList);

        playButton.setText("Play"); // NOI18N
        playButton.setName("playButton"); // NOI18N

        puzzleListDescriptionLabel.setText("Select a puzzle to solve:"); // NOI18N
        puzzleListDescriptionLabel.setName("puzzleListDescriptionLabel"); // NOI18N

        mainSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        mainSeparator.setName("mainSeparator"); // NOI18N

        playGameOnServer.setFont(boldFont); // NOI18N
        playGameOnServer.setText("Play game on a server"); // NOI18N
        playGameOnServer.setName("playGameOnServer"); // NOI18N

        serverAddressLabel.setText("Server address:"); // NOI18N
        serverAddressLabel.setName("serverAddressLabel"); // NOI18N

        serverAddressScrollPane.setName("serverAddressScrollPane"); // NOI18N

        serverAddressTextBox.setName("serverAddressTextBox"); // NOI18N
        serverAddressScrollPane.setViewportView(serverAddressTextBox);

        connectToServerButton.setText("Connect"); // NOI18N
        connectToServerButton.setName("connectToServerButton"); // NOI18N

        editPuzzleButton.setText("Create/edit a puzzle"); // NOI18N
        editPuzzleButton.setName("editPuzzleButton"); // NOI18N

        postPaneScrollPane.setName("postPaneScrollPane"); // NOI18N

        portTextField.setName("portTextField"); // NOI18N
        postPaneScrollPane.setViewportView(portTextField);

        portLabel.setText("Port:"); // NOI18N
        portLabel.setName("portLabel"); // NOI18N

        createServerButton.setText("Create server"); // NOI18N
        createServerButton.setName("createServerButton"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(playLocalGameLabel)
                                .addComponent(puzzleListDescriptionLabel)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(portLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(postPaneScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(createServerButton))
                                .addComponent(puzzleListScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editPuzzleButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(playButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mainSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playGameOnServer)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(serverAddressLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(serverAddressScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(connectToServerButton))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mainMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playGameOnServer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(serverAddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(serverAddressScrollPane))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(connectToServerButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(mainSeparator, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(playLocalGameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(puzzleListDescriptionLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(puzzleListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(editPuzzleButton)
                                .addComponent(playButton))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(createServerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(postPaneScrollPane)
                                .addComponent(portLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)))))
                .addContainerGap())
        );
    }// </editor-fold>
    // Variables declaration - do not modify
    public static javax.swing.JButton connectToServerButton;
    public static javax.swing.JButton createServerButton;
    public static javax.swing.JButton editPuzzleButton;
    public static javax.swing.JLabel mainMenuLabel;
    public static javax.swing.JSeparator mainSeparator;
    public static javax.swing.JButton playButton;
    public static javax.swing.JLabel playGameOnServer;
    public static javax.swing.JLabel playLocalGameLabel;
    public static javax.swing.JLabel portLabel;
    public static javax.swing.JTextPane portTextField;
    public static javax.swing.JScrollPane postPaneScrollPane;
    public static javax.swing.JList puzzleList;
    public static javax.swing.JLabel puzzleListDescriptionLabel;
    public static javax.swing.JScrollPane puzzleListScrollPane;
    public static javax.swing.JLabel serverAddressLabel;
    public static javax.swing.JScrollPane serverAddressScrollPane;
    public static javax.swing.JTextPane serverAddressTextBox;
    // End of variables declaration
}
